// <auto-generated />
namespace SalaoBeleza.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updating_Model_Booking_DataAnnotations_RequiredCUstomerID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updating_Model_Booking_DataAnnotations_RequiredCUstomerID));
        
        string IMigrationMetadata.Id
        {
            get { return "201708241415087_updating_Model_Booking_DataAnnotations_RequiredCUstomerID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
